apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: sitharosrey
spec:
  dnsNames:
    - who.auto-pilot.dev
  secretName: tls-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
